services:

    shinobi-countdown-timers:

        container_name: shinobi-countdown-timers
        
        image: softwareshinobi/shinobi-countdown-timers

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - "8080:80"
