services:

    clocks.softwareshinobi.com:

        container_name: clocks.softwareshinobi.com

        image: softwareshinobi/clocks.softwareshinobi.com

        build:

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        ports:

            - "8000:80"
