
services:

    clocks.softwareshinobi.digital:

        container_name: clocks.softwareshinobi.digital
        
        image: softwareshinobi/clocks.softwareshinobi.digital

        build: 

            context: .

            dockerfile: Dockerfile
    
        restart: unless-stopped

        ports:

            - "8080:80"
